<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <AssemblyName>ChatGPTMulti</AssemblyName>
    <RootNamespace>ChatGPTMulti</RootNamespace>
    <RestorePackagesWithLockFile>true</RestorePackagesWithLockFile>
    <DefaultItemExcludes>$(DefaultItemExcludes);tests\**;.artifacts\**</DefaultItemExcludes>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.Web.WebView2" Version="1.0.4191.47" />
    <InternalsVisibleTo Include="ChatGPTMulti.Tests" />
  </ItemGroup>
</Project>
