# -*- coding: utf-8 -*-
"""Chen_TwoComplement_ClassExercise.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1LbqL9NhwhqyS6CFO7VeteKyhWPDYiRkM
"""

# Author:         Ryan Chen
# Date:          9/11/2023
# Description:    Conversions
# Revision History
# Name      Date        Comment
# -    -    -    -    -    -    -    -    -    -
# Ryan 9/18/2023 Worked Independantly to Complete Binary to Decimal 
# Ryan 9/20/2023 Worked in clas to complete twos complement 
# -    -    -    -    -    -    -    -    -    -

#import numpy as np
#import pandas as pd
#import seaborn as sns

MAX = 255

# Add your bespoke functions here
# -   -   -   -   -   -   -   -   -   -   -   -   -   -   -   -   -
def invertComplement(bin):
  complement = []
  for n in bin:
    if n == 0:
      complement.append(1)
    else:
      complement.append(0)

  return complement

#-------------------------------------------------------------
def convertToBinary(integer):
  bin_list =[]

  if integer < 0 or integer > MAX:
    raise ValueError("Enter an integer between 0 and 255")
  if integer <= MAX:
    q = 99999
    r = 0
    while q != 0:
      q = integer // 2
      r = integer % 2
      integer = q
      bin_list.append(r)

  bin_list.reverse()
  return bin_list
# -   -   -   -   -   -   -   -   -   -   -   -   -   -   -   -   -

def convertToDecimal(binary):
#reads the binary digits supplied by the caller
  number = ''.join(str(digit) for digit in binary)
#converts the binary digits to a decimal integer
  x = int(number,2)
#prints sentence along with binary after conversion
  print('The binary is equal to ',x)



  return x
# -   -   -   -   -   -   -   -   -   -   -   -   -   -   -   -   -

def convertToTwosComplement(i):
  """Return the eight-bit two's complement of the input's magnitude."""
  #Step 0: take absolute value
  i = abs(i)

  #Step 1: Convert to binary
  twosComplement = convertToBinary(i)
  twosComplement = [0] * (8 - len(twosComplement)) + twosComplement
  twosComplement = invertComplement(twosComplement)

  #Step 2: Add one, keeping the result eight bits wide
  carry = 1
  for index in range(7, -1, -1):
    total = twosComplement[index] + carry
    twosComplement[index] = total % 2
    carry = total // 2

  return twosComplement
# -   -   -   -   -   -   -   -   -   -   -   -   -   -   -   -   -

def main(n):

  print('The decimal number :',n)

  b = convertToBinary(n)
  n = convertToDecimal(b)

  print('The is binary      :',b)

#decimal = np.random.randint(1,MAX)

decimal = 7
if __name__ == "__main__":
  main(decimal)
